# JSON examples and exercise
****
+ get familiar with packages for dealing with JSON
+ study examples with JSON strings and files 
+ work on exercise to be completed and submitted 
****
+ reference: http://pandas.pydata.org/pandas-docs/stable/io.html#io-json-reader
+ data source: http://jsonstudio.com/resources/
****

In [40]:
import pandas as pd

## imports for Python, Pandas

In [41]:
import json
from pandas.io.json import json_normalize

## JSON example, with string

+ demonstrates creation of normalized dataframes (tables) from nested json string
+ source: http://pandas.pydata.org/pandas-docs/stable/io.html#normalization

In [42]:
# define json string
data = [{'state': 'Florida', 
         'shortname': 'FL',
         'info': {'governor': 'Rick Scott'},
         'counties': [{'name': 'Dade', 'population': 12345},
                      {'name': 'Broward', 'population': 40000},
                      {'name': 'Palm Beach', 'population': 60000}]},
        {'state': 'Ohio',
         'shortname': 'OH',
         'info': {'governor': 'John Kasich'},
         'counties': [{'name': 'Summit', 'population': 1234},
                      {'name': 'Cuyahoga', 'population': 1337}]}]

In [43]:
# use normalization to create tables from nested element
json_normalize(data, 'counties')

         name  population
0        Dade       12345
1     Broward       40000
2  Palm Beach       60000
3      Summit        1234
4    Cuyahoga        1337

In [44]:
# further populate tables created from nested element
json_normalize(data, 'counties', ['state', 'shortname', ['info', 'governor']])

         name  population    state shortname info.governor
0        Dade       12345  Florida        FL    Rick Scott
1     Broward       40000  Florida        FL    Rick Scott
2  Palm Beach       60000  Florida        FL    Rick Scott
3      Summit        1234     Ohio        OH   John Kasich
4    Cuyahoga        1337     Ohio        OH   John Kasich

****
## JSON example, with file

+ demonstrates reading in a json file as a string and as a table
+ uses small sample file containing data about projects funded by the World Bank 
+ data source: http://jsonstudio.com/resources/

In [45]:
# load json as string
json.load((open(r'C:\Users\kenew\Documents\gwaith_cwrs_iwan\data_wrangling_json\data_wrangling_json\data\world_bank_projects_less.json')))

[{'_id': {'$oid': '52b213b38594d8a2be17c780'},
  'approvalfy': 1999,
  'board_approval_month': 'November',
  'boardapprovaldate': '2013-11-12T00:00:00Z',
  'borrower': 'FEDERAL DEMOCRATIC REPUBLIC OF ETHIOPIA',
  'closingdate': '2018-07-07T00:00:00Z',
  'country_namecode': 'Federal Democratic Republic of Ethiopia!$!ET',
  'countrycode': 'ET',
  'countryname': 'Federal Democratic Republic of Ethiopia',
  'countryshortname': 'Ethiopia',
  'docty': 'Project Information Document,Indigenous Peoples Plan,Project Information Document',
  'envassesmentcategorycode': 'C',
  'grantamt': 0,
  'ibrdcommamt': 0,
  'id': 'P129828',
  'idacommamt': 130000000,
  'impagency': 'MINISTRY OF EDUCATION',
  'lendinginstr': 'Investment Project Financing',
  'lendinginstrtype': 'IN',
  'lendprojectcost': 550000000,
  'majorsector_percent': [{'Name': 'Education', 'Percent': 46},
   {'Name': 'Education', 'Percent': 26},
   {'Name': 'Public Administration, Law, and Justice', 'Percent': 16},
   {'Name': 'Education', 'Percent': 12}],
  'mjsector_namecode': [{'code': 'EX', 'name': 'Education'},
   {'code': 'EX', 'name': 'Education'},
   {'code': 'BX', 'name': 'Public Administration, Law, and Justice'},
   {'code': 'EX', 'name': 'Education'}],
  'mjtheme': ['Human development'],
  'mjtheme_namecode': [{'code': '8', 'name': 'Human development'},
   {'code': '11', 'name': ''}],
  'mjthemecode': '8,11',
  'prodline': 'PE',
  'prodlinetext': 'IBRD/IDA',
  'productlinetype': 'L',
  'project_abstract': {'cdata': 'The development objective of the Second Phase of General Education Quality Improvement Project for Ethiopia is to improve learning conditions in primary and secondary schools and strengthen institutions at different levels of educational administration. The project has six components. The first component is curriculum, textbooks, assessment, examinations, and inspection. This component will support improvement of learning conditions in grades KG-12 by providing increased access to teaching and learning materials and through improvements to the curriculum by assessing the strengths and weaknesses of the current curriculum. This component has following four sub-components: (i) curriculum reform and implementation; (ii) teaching and learning materials; (iii) assessment and examinations; and (iv) inspection. The second component is teacher development program (TDP). This component will support improvements in learning conditions in both primary and secondary schools by advancing the quality of teaching in general education through: (a) enhancing the training of pre-service teachers in teacher education institutions; and (b) improving the quality of in-service teacher training. This component has following three sub-components: (i) pre-service teacher training; (ii) in-service teacher training; and (iii) licensing and relicensing of teachers and school leaders. The third component is school improvement plan. This component will support the strengthening of school planning in order to improve learning outcomes, and to partly fund the school improvement plans through school grants. It has following two sub-components: (i) school improvement plan; and (ii) school grants. The fourth component is management and capacity building, including education management information systems (EMIS). This component will support management and capacity building aspect of the project. This component has following three sub-components: (i) capacity building for education planning and management; (ii) capacity building for school planning and management; and (iii) EMIS. The fifth component is improving the quality of learning and teaching in secondary schools and universities through the use of information and communications technology (ICT). It has following five sub-components: (i) national policy and institution for ICT in general education; (ii) national ICT infrastructure improvement plan for general education; (iii) develop an integrated monitoring, evaluation, and learning system specifically for the ICT component; (iv) teacher professional development in the use of ICT; and (v) provision of limited number of e-Braille display readers with the possibility to scale up to all secondary education schools based on the successful implementation and usage of the readers. The sixth component is program coordination, monitoring and evaluation, and communication. It will support institutional strengthening by developing capacities in all aspects of program coordination, monitoring and evaluation; a new sub-component on communications will support information sharing for better management and accountability. It has following three sub-components: (i) program coordination; (ii) monitoring and evaluation (M and E); and (iii) communication.'},
  'project_name': 'Ethiopia General Education Quality Improvement Project II',
  'projectdocs': [{'DocDate': '28-AUG-2013',
    'DocType': 'PID',
    'DocTypeDesc': 'Project Information Document (PID),  Vol.',
    'DocURL': 'http://www-wds.worldbank.org/servlet/WDSServlet?pcont=details&eid=090224b081e545fb_1_0',
    'EntityID': '090224b081e545fb_1_0'},
   {'DocDate': '01-JUL-2013',
    'DocType': 'IP',
    'DocTypeDesc': 'Indigenous Peoples Plan (IP),  Vol.1 of 1',
    'DocURL': 'http://www-wds.worldbank.org/servlet/WDSServlet?pcont=details&eid=000442464_20130920111729',
    'EntityID': '000442464_20130920111729'},
   {'DocDate': '22-NOV-2012',
    'DocType': 'PID',
    'DocTypeDesc': 'Project Information Document (PID),  Vol.',
    'DocURL': 'http://www-wds.worldbank.org/servlet/WDSServlet?pcont=details&eid=090224b0817b19e2_1_0',
    'EntityID': '090224b0817b19e2_1_0'}],
  'projectfinancialtype': 'IDA',
  'projectstatusdisplay': 'Active',
  'regionname': 'Africa',
  'sector': [{'Name': 'Primary education'},
   {'Name': 'Secondary education'},
   {'Name': 'Public administration- Other social services'},
   {'Name': 'Tertiary education'}],
  'sector1': {'Name': 'Primary education', 'Percent': 46},
  'sector2': {'Name': 'Secondary education', 'Percent': 26},
  'sector3': {'Name': 'Public administration- Other social services',
   'Percent': 16},
  'sector4': {'Name': 'Tertiary education', 'Percent': 12},
  'sector_namecode': [{'code': 'EP', 'name': 'Primary education'},
   {'code': 'ES', 'name': 'Secondary education'},
   {'code': 'BS', 'name': 'Public administration- Other social services'},
   {'code': 'ET', 'name': 'Tertiary education'}],
  'sectorcode': 'ET,BS,ES,EP',
  'source': 'IBRD',
  'status': 'Active',
  'supplementprojectflg': 'N',
  'theme1': {'Name': 'Education for all', 'Percent': 100},
  'theme_namecode': [{'code': '65', 'name': 'Education for all'}],
  'themecode': '65',
  'totalamt': 130000000,
  'totalcommamt': 130000000,
  'url': 'http://www.worldbank.org/projects/P129828/ethiopia-general-education-quality-improvement-project-ii?lang=en'},
 {'_id': {'$oid': '52b213b38594d8a2be17c781'},
  'approvalfy': 2015,
  'board_approval_month': 'November',
  'boardapprovaldate': '2013-11-04T00:00:00Z',
  'borrower': 'GOVERNMENT OF TUNISIA',
  'country_namecode': 'Republic of Tunisia!$!TN',
  'countrycode': 'TN',
  'countryname': 'Republic of Tunisia',
  'countryshortname': 'Tunisia',
  'docty': 'Project Information Document,Integrated Safeguards Data Sheet,Integrated Safeguards Data Sheet,Project Information Document,Integrated Safeguards Data Sheet,Project Information Document',
  'envassesmentcategorycode': 'C',
  'grantamt': 4700000,
  'ibrdcommamt': 0,
  'id': 'P144674',
  'idacommamt': 0,
  'impagency': 'MINISTRY OF FINANCE',
  'lendinginstr': 'Specific Investment Loan',
  'lendinginstrtype': 'IN',
  'lendprojectcost': 5700000,
  'majorsector_percent': [{'Name': 'Public Administration, Law, and Justice',
    'Percent': 70},
   {'Name': 'Public Administration, Law, and Justice', 'Percent': 30}],
  'mjsector_namecode': [{'code': 'BX',
    'name': 'Public Administration, Law, and Justice'},
   {'code': 'BX', 'name': 'Public Administration, Law, and Justice'}],
  'mjtheme': ['Economic management', 'Social protection and risk management'],
  'mjtheme_namecode': [{'code': '1', 'name': 'Economic management'},
   {'code': '6', 'name': 'Social protection and risk management'}],
  'mjthemecode': '1,6',
  'prodline': 'RE',
  'prodlinetext': 'Recipient Executed Activities',
  'productlinetype': 'L',
  'project_name': 'TN: DTF Social Protection Reforms Support',
  'projectdocs': [{'DocDate': '29-MAR-2013',
    'DocType': 'PID',
    'DocTypeDesc': 'Project Information Document (PID),  Vol.1 of 1',
    'DocURL': 'http://www-wds.worldbank.org/servlet/WDSServlet?pcont=details&eid=000333037_20131024115616',
    'EntityID': '000333037_20131024115616'},
   {'DocDate': '29-MAR-2013',
    'DocType': 'ISDS',
    'DocTypeDesc': 'Integrated Safeguards Data Sheet (ISDS),  Vol.1 of 1',
    'DocURL': 'http://www-wds.worldbank.org/servlet/WDSServlet?pcont=details&eid=000356161_20131024151611',
    'EntityID': '000356161_20131024151611'},
   {'DocDate': '29-MAR-2013',
    'DocType': 'ISDS',
    'DocTypeDesc': 'Integrated Safeguards Data Sheet (ISDS),  Vol.1 of 1',
    'DocURL': 'http://www-wds.worldbank.org/servlet/WDSServlet?pcont=details&eid=000442464_20131031112136',
    'EntityID': '000442464_20131031112136'},
   {'DocDate': '29-MAR-2013',
    'DocType': 'PID',
    'DocTypeDesc': 'Project Information Document (PID),  Vol.1 of 1',
    'DocURL': 'http://www-wds.worldbank.org/servlet/WDSServlet?pcont=details&eid=000333037_20131031105716',
    'EntityID': '000333037_20131031105716'},
   {'DocDate': '16-JAN-2013',
    'DocType': 'ISDS',
    'DocTypeDesc': 'Integrated Safeguards Data Sheet (ISDS),  Vol.1 of 1',
    'DocURL': 'http://www-wds.worldbank.org/servlet/WDSServlet?pcont=details&eid=000356161_20130305113209',
    'EntityID': '000356161_20130305113209'},
   {'DocDate': '16-JAN-2013',
    'DocType': 'PID',
    'DocTypeDesc': 'Project Information Document (PID),  Vol.1 of 1',
    'DocURL': 'http://www-wds.worldbank.org/servlet/WDSServlet?pcont=details&eid=000356161_20130305113716',
    'EntityID': '000356161_20130305113716'}],
  'projectfinancialtype': 'OTHER',
  'projectstatusdisplay': 'Active',
  'regionname': 'Middle East and North Africa',
  'sector': [{'Name': 'Public administration- Other social services'},
   {'Name': 'General public administration sector'}],
  'sector1': {'Name': 'Public administration- Other social services',
   'Percent': 70},
  'sector2': {'Name': 'General public administration sector', 'Percent': 30},
  'sector_namecode': [{'code': 'BS',
    'name': 'Public administration- Other social services'},
   {'code': 'BZ', 'name': 'General public administration sector'}],
  'sectorcode': 'BZ,BS',
  'source': 'IBRD',
  'status': 'Active',
  'supplementprojectflg': 'N',
  'theme1': {'Name': 'Other economic management', 'Percent': 30},
  'theme_namecode': [{'code': '24', 'name': 'Other economic management'},
   {'code': '54', 'name': 'Social safety nets'}],
  'themecode': '54,24',
  'totalamt': 0,
  'totalcommamt': 4700000,
  'url': 'http://www.worldbank.org/projects/P144674?lang=en'}]

In [46]:
# load as Pandas dataframe
sample_json_df = pd.read_json(r'C:\Users\kenew\Documents\gwaith_cwrs_iwan\data_wrangling_json\data_wrangling_json\data\world_bank_projects_less.json')
sample_json_df

,_id,approvalfy,board_approval_month,boardapprovaldate,borrower,closingdate,country_namecode,countrycode,countryname,countryshortname,...,sectorcode,source,status,supplementprojectflg,theme1,theme_namecode,themecode,totalamt,totalcommamt,url
0,{'$oid': '52b213b38594d8a2be17c780'},1999,November,2013-11-12T00:00:00Z,FEDERAL DEMOCRATIC REPUBLIC OF ETHIOPIA,2018-07-07T00:00:00Z,Federal Democratic Republic of Ethiopia!$!ET,ET,Federal Democratic Republic of Ethiopia,Ethiopia,...,"ET,BS,ES,EP",IBRD,Active,N,"{'Name': 'Education for all', 'Percent': 100}","[{'name': 'Education for all', 'code': '65'}]",65,130000000,130000000,http://www.worldbank.org/projects/P129828/ethi...
1,{'$oid': '52b213b38594d8a2be17c781'},2015,November,2013-11-04T00:00:00Z,GOVERNMENT OF TUNISIA,NaN,Republic of Tunisia!$!TN,TN,Republic of Tunisia,Tunisia,...,"BZ,BS",IBRD,Active,N,"{'Name': 'Other economic management', 'Percent...","[{'name': 'Other economic management', 'code':...","54,24",0,4700000,http://www.worldbank.org/projects/P144674?lang=en

****
## JSON exercise

Using data in file 'data/world_bank_projects.json' and the techniques demonstrated above,
1. Find the 10 countries with most projects
2. Find the top 10 major project themes (using column 'mjtheme_namecode')
3. In 2. above you will notice that some entries have only the code and the name is missing. Create a dataframe with the missing names filled in.

In [47]:
json_df = pd.read_json(r'C:\Users\kenew\Documents\gwaith_cwrs_iwan\data_wrangling_json\data_wrangling_json\data\world_bank_projects.json')
#loaded the json

print(json_df.columns)
#checking the column names

json_df.groupby(['countryname']).size().sort_values(ascending=False).head(10)

#grouping the country names, unpacking and ordering by values to then output the countries with the most projects.

Index(['_id', 'approvalfy', 'board_approval_month', 'boardapprovaldate',
       'borrower', 'closingdate', 'country_namecode', 'countrycode',
       'countryname', 'countryshortname', 'docty', 'envassesmentcategorycode',
       'grantamt', 'ibrdcommamt', 'id', 'idacommamt', 'impagency',
       'lendinginstr', 'lendinginstrtype', 'lendprojectcost',
       'majorsector_percent', 'mjsector_namecode', 'mjtheme',
       'mjtheme_namecode', 'mjthemecode', 'prodline', 'prodlinetext',
       'productlinetype', 'project_abstract', 'project_name', 'projectdocs',
       'projectfinancialtype', 'projectstatusdisplay', 'regionname', 'sector',
       'sector1', 'sector2', 'sector3', 'sector4', 'sector_namecode',
       'sectorcode', 'source', 'status', 'supplementprojectflg', 'theme1',
       'theme_namecode', 'themecode', 'totalamt', 'totalcommamt', 'url'],
      dtype='object')

countryname
People's Republic of China         19
Republic of Indonesia              19
Socialist Republic of Vietnam      17
Republic of India                  16
Republic of Yemen                  13
Nepal                              12
People's Republic of Bangladesh    12
Kingdom of Morocco                 12
Africa                             11
Republic of Mozambique             11
dtype: int64

In [85]:
#loading and normalizing the dataset of the namecode as described in the json normalizing instructions.
#checking to see what the dataset looks like.

json_string = json.load((open(r'C:\Users\kenew\Documents\gwaith_cwrs_iwan\data_wrangling_json\data_wrangling_json\data\world_bank_projects.json')))
normalized_ver = json_normalize(json_string, 'mjtheme_namecode', ['id'])
print(normalized_ver.head(10))

  code                                          name       id
0    8                             Human development  P129828
1   11                                                P129828
2    1                           Economic management  P144674
3    6         Social protection and risk management  P144674
4    5                         Trade and integration  P145310
5    2                      Public sector governance  P145310
6   11  Environment and natural resources management  P145310
7    6         Social protection and risk management  P145310
8    7                   Social dev/gender/inclusion  P144665
9    7                   Social dev/gender/inclusion  P144665

In [79]:
normalized_ver.groupby(['name']).size().sort_values(ascending=False).head(10)

#like before, grouping and unpacking, then sorting the values to see the top 10 most common project names

name
Environment and natural resources management    223
Rural development                               202
Human development                               197
Public sector governance                        184
Social protection and risk management           158
Financial and private sector development        130
                                                122
Social dev/gender/inclusion                     119
Trade and integration                            72
Urban development                                47
dtype: int64

In [80]:
projects = normalized_ver[['code', 'name']]
#selecting the code and name only, to drop the duplicates and get a table of the codes and names.

In [93]:
projects = projects.drop_duplicates().dropna(axis=0, how='any')

#dropping the duplicates and na's to obtain a table of the codes and associated names.

print(projects)

    code                                          name
0      8                             Human development
1     11
2      1                           Economic management
3      6         Social protection and risk management
4      5                         Trade and integration
5      2                      Public sector governance
6     11  Environment and natural resources management
8      7                   Social dev/gender/inclusion
11     4      Financial and private sector development
13     6
17     8
18    10                             Rural development
19     7
24     2
29     4
53     9                             Urban development
121   10
201    5
212    1
252    3                                   Rule of law
333    9
493    3

In [98]:
pd.merge(projects, normalized_ver, left_on='name', right_on='name')

#merging the data together to ensure the names are with their associated codes.

     code_x               name code_y       id
0         8  Human development      8  P129828
1         8  Human development      8  P132616
2         8  Human development      8  P146271
3         8  Human development      8  P146271
4         8  Human development      8  P146271
5         8  Human development      8  P146109
6         8  Human development      8  P146109
7         8  Human development      8  P143025
8         8  Human development      8  P122700
9         8  Human development      8  P145118
10        8  Human development      8  P128628
11        8  Human development      8  P125018
12        8  Human development      8  P132753
13        8  Human development      8  P132753
14        8  Human development      8  P132753
15        8  Human development      8  P131202
16        8  Human development      8  P126130
17        8  Human development      8  P126130
18        8  Human development      8  P126130
19        8  Human development      8  P126034
20        8  Human development      8  P131212
21        8  Human development      8  P131441
22        8  Human development      8  P144532
23        8  Human development      8  P144532
24        8  Human development      8  P123503
25        8  Human development      8  P120397
26        8  Human development      8  P143060
27        8  Human development      8  P143060
28        8  Human development      8  P126452
29        8  Human development      8  P126452
...     ...                ...    ...      ...
2689      9  Urban development      9  P127955
2690      9  Urban development      9  P132268
2691      9  Urban development      9  P130819
2692      9  Urban development      9  P130972
2693      9  Urban development      9  P130972
2694      9  Urban development      9  P130972
2695      9  Urban development      9  P101289
2696      9  Urban development      9  P118152
2697      9  Urban development      9  P130528
2698      9  Urban development      9  P130461
2699      9  Urban development      9  P130174
2700      9  Urban development      9  P131394
2701      9  Urban development      9  P112901
2702      9  Urban development      9  P112901
2703      9  Urban development      9  P118916
2704      9  Urban development      9  P128763
2705      9  Urban development      9  P128763
2706      9  Urban development      9  P126321
2707      3        Rule of law      3  P128443
2708      3        Rule of law      3  P130459
2709      3        Rule of law      3  P127787
2710      3        Rule of law      3  P144386
2711      3        Rule of law      3  P144386
2712      3        Rule of law      3  P121152
2713      3        Rule of law      3  P105269
2714      3        Rule of law      3  P128950
2715      3        Rule of law      3  P130528
2716      3        Rule of law      3  P131767
2717      3        Rule of law      3  P125202
2718      3        Rule of law      3  P131266

[2719 rows x 4 columns]